#!/bin/bash

# Test script to help debug key codes
echo "Key code debugging helper"
echo "========================="
echo ""
echo "This script will help identify key codes for resize functionality."
echo "After running this script in the script runner:"
echo ""
echo "1. Press F1 or ? to open help"
echo "2. Try pressing Ctrl+Left Arrow and Ctrl+Right Arrow"
echo "3. Check the log file to see what key codes are received"
echo ""
echo "Expected key codes:"
echo "  Ctrl+Left:  545"  
echo "  Ctrl+Right: 560"
echo ""
echo "If resize doesn't work, the actual key codes on your system"
echo "might be different and need to be updated in the source code."
echo ""
echo "Log location: ./script_runner.log"
echo ""
echo "You can also try these alternative combinations:"
echo "  Shift+Left/Right"
echo "  Alt+Left/Right" 
echo "  Ctrl+Shift+Left/Right"
echo ""
echo "Press any key to continue or Ctrl+Q to quit..."
read -n 1
